"""Utility submodule exports for backward compatibility."""

from .common import logger, get_user_display_name
from .security import (
    hash,
    verify,
    generate_encryption_key,
    update_encryption_key,
    admin_required,
    handle_exceptions,
    pwd_context,
)
from .files import generate_qr_code, save_upload_file, UPLOAD_ROOT
from .content import (
    sentiment_pipeline,
    check_content_against_rules,
    detect_language,
    train_content_classifier,
    check_for_profanity,
    validate_urls,
    is_valid_image_url,
    is_valid_video_url,
    analyze_sentiment,
    process_mentions,
    is_content_offensive,
    get_or_create_hashtag,
    update_repost_statistics,
    send_repost_notification,
)
from .analytics import (
    create_default_categories,
    update_user_statistics,
    analyze_user_behavior,
    calculate_post_score,
    update_post_score,
    update_post_vote_statistics,
    get_user_vote_analytics,
    create_post_vote_analytics,
    CallQualityBuffer,
    quality_buffers,
    check_call_quality,
    should_adjust_video_quality,
    get_recommended_video_quality,
    clean_old_quality_buffers,
    QUALITY_WINDOW_SIZE,
    MIN_QUALITY_THRESHOLD,
)
from .network import get_client_ip, is_ip_banned, detect_ip_evasion
from .search import (
    spell,
    search_cache,
    update_search_vector,
    search_posts,
    get_spell_suggestions,
    format_spell_suggestions,
    sort_search_results,
)
from .translation import translation_cache, cached_translate_text, get_translated_content
from .links import update_link_preview
from .events import log_user_event
from .moderation import log_event, log_admin_action

__all__ = [
    "logger",
    "get_user_display_name",
    "hash",
    "verify",
    "generate_encryption_key",
    "update_encryption_key",
    "admin_required",
    "handle_exceptions",
    "pwd_context",
    "generate_qr_code",
    "save_upload_file",
    "UPLOAD_ROOT",
    "sentiment_pipeline",
    "check_content_against_rules",
    "detect_language",
    "train_content_classifier",
    "check_for_profanity",
    "validate_urls",
    "is_valid_image_url",
    "is_valid_video_url",
    "analyze_sentiment",
    "process_mentions",
    "is_content_offensive",
    "get_or_create_hashtag",
    "update_repost_statistics",
    "send_repost_notification",
    "create_default_categories",
    "update_user_statistics",
    "analyze_user_behavior",
    "calculate_post_score",
    "update_post_score",
    "update_post_vote_statistics",
    "get_user_vote_analytics",
    "create_post_vote_analytics",
    "CallQualityBuffer",
    "quality_buffers",
    "check_call_quality",
    "should_adjust_video_quality",
    "get_recommended_video_quality",
    "clean_old_quality_buffers",
    "QUALITY_WINDOW_SIZE",
    "MIN_QUALITY_THRESHOLD",
    "get_client_ip",
    "is_ip_banned",
    "detect_ip_evasion",
    "spell",
    "search_cache",
    "update_search_vector",
    "search_posts",
    "get_spell_suggestions",
    "format_spell_suggestions",
    "sort_search_results",
    "translation_cache",
    "cached_translate_text",
    "get_translated_content",
    "update_link_preview",
    "log_user_event",
]
