"""Add link preview to messages

Revision ID: 204a27cb0fe6
Revises: d3dbe9cc995d
Create Date: 2024-10-13 07:38:53.162017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204a27cb0fe6'
down_revision: Union[str, None] = 'd3dbe9cc995d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('link_preview', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'link_preview')
    # ### end Alembic commands ###
