"""Add location support to messages

Revision ID: 2da5deab88b4
Revises: 3e7bb33b73f3
Create Date: 2024-10-10 03:44:50.337014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da5deab88b4'
down_revision: Union[str, None] = '3e7bb33b73f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'longitude')
    op.drop_column('messages', 'latitude')
    # ### end Alembic commands ###
