"""Add is_edited column to messages

Revision ID: 533038e4f110
Revises: bce76be66345
Create Date: 2024-10-10 19:02:06.646995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533038e4f110'
down_revision: Union[str, None] = 'bce76be66345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_edited')
    # ### end Alembic commands ###
