"""Add conversation_id and indexes to messages

Revision ID: 65a5e879a085
Revises: 70daf18fd325
Create Date: 2024-10-11 01:35:41.768673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum

# revision identifiers, used by Alembic.
revision: str = "65a5e879a085"
down_revision: Union[str, None] = "70daf18fd325"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the Enum type first
    message_type = Enum("TEXT", "IMAGE", "FILE", "STICKER", name="messagetype")
    message_type.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "message_type",
            sa.Enum("TEXT", "IMAGE", "FILE", "STICKER", name="messagetype"),
            nullable=False,
            server_default="TEXT",
        ),
    )
    op.add_column("messages", sa.Column("file_url", sa.String(), nullable=True))
    op.add_column("messages", sa.Column("conversation_id", sa.String(), nullable=True))

    # Create gin index for content column
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index(
        "idx_message_content",
        "messages",
        ["content"],
        unique=False,
        postgresql_ops={"content": "gin_trgm_ops"},
        postgresql_using="gin",
    )

    op.create_index("idx_message_timestamp", "messages", ["timestamp"], unique=False)
    op.create_index(
        op.f("ix_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index("idx_message_timestamp", table_name="messages")
    op.drop_index("idx_message_content", table_name="messages")
    op.drop_column("messages", "conversation_id")
    op.drop_column("messages", "file_url")
    op.drop_column("messages", "message_type")

    # Drop the Enum type
    message_type = Enum("TEXT", "IMAGE", "FILE", "STICKER", name="messagetype")
    message_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
