"""Add sticker categories and reports

Revision ID: 70daf18fd325
Revises: bb1caf10f6dc
Create Date: 2024-10-10 20:16:53.985869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70daf18fd325'
down_revision: Union[str, None] = 'bb1caf10f6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sticker_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sticker_categories_id'), 'sticker_categories', ['id'], unique=False)
    op.create_index(op.f('ix_sticker_categories_name'), 'sticker_categories', ['name'], unique=True)
    op.create_table('sticker_category_association',
    sa.Column('sticker_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['sticker_categories.id'], ),
    sa.ForeignKeyConstraint(['sticker_id'], ['stickers.id'], )
    )
    op.create_table('sticker_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sticker_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sticker_id'], ['stickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sticker_reports_id'), 'sticker_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sticker_reports_id'), table_name='sticker_reports')
    op.drop_table('sticker_reports')
    op.drop_table('sticker_category_association')
    op.drop_index(op.f('ix_sticker_categories_name'), table_name='sticker_categories')
    op.drop_index(op.f('ix_sticker_categories_id'), table_name='sticker_categories')
    op.drop_table('sticker_categories')
    # ### end Alembic commands ###
