from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "84aefd12416d"
down_revision = "03d30771b8a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("email", sa.String, unique=True, index=True),
        sa.Column("password", sa.String),
        sa.Column("phone_number", sa.String, nullable=True),
    )

    op.create_table(
        "posts",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("title", sa.String, index=True),
        sa.Column("content", sa.String, index=True),
        sa.Column("owner_id", sa.Integer, sa.ForeignKey("users.id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    op.drop_table
