"""Add EncryptedSession model

Revision ID: 8694710b1b91
Revises: 5e3885cc2a87
Create Date: 2024-10-12 11:18:11.842934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8694710b1b91'
down_revision: Union[str, None] = '5e3885cc2a87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encrypted_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('other_user_id', sa.Integer(), nullable=True),
    sa.Column('root_key', sa.LargeBinary(), nullable=True),
    sa.Column('chain_key', sa.LargeBinary(), nullable=True),
    sa.Column('next_header_key', sa.LargeBinary(), nullable=True),
    sa.Column('ratchet_key', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['other_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypted_sessions_id'), 'encrypted_sessions', ['id'], unique=False)
    op.add_column('messages', sa.Column('encrypted_content', sa.LargeBinary(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('public_key', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_key')
    op.drop_column('users', 'hashed_password')
    op.drop_column('messages', 'encrypted_content')
    op.drop_index(op.f('ix_encrypted_sessions_id'), table_name='encrypted_sessions')
    op.drop_table('encrypted_sessions')
    # ### end Alembic commands ###
