"""Add skills and interests to User model

Revision ID: 93d8dedbdc72
Revises: 8ad9ce9a7d67
Create Date: 2024-10-08 03:23:50.391914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d8dedbdc72'
down_revision: Union[str, None] = '8ad9ce9a7d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('interests', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    op.drop_column('users', 'skills')
    # ### end Alembic commands ###
