"""Add additional location fields to messages

Revision ID: afe7d58e94ea
Revises: 2da5deab88b4
Create Date: 2024-10-10 18:27:52.220180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afe7d58e94ea'
down_revision: Union[str, None] = '2da5deab88b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_current_location', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('location_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'location_name')
    op.drop_column('messages', 'is_current_location')
    # ### end Alembic commands ###
