"""Add 2FA fields to User model

Revision ID: ba8a5216b091
Revises: 2b37ac7eeebd
Create Date: 2024-10-07 19:41:01.165368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8a5216b091'
down_revision: Union[str, None] = '2b37ac7eeebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_2fa_enabled')
    # ### end Alembic commands ###
