"""Add sticker packs and approval system

Revision ID: bb1caf10f6dc
Revises: 82b239ec69eb
Create Date: 2024-10-10 20:09:14.002060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1caf10f6dc'
down_revision: Union[str, None] = '82b239ec69eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sticker_packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sticker_packs_id'), 'sticker_packs', ['id'], unique=False)
    op.create_index(op.f('ix_sticker_packs_name'), 'sticker_packs', ['name'], unique=False)
    op.create_table('stickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pack_id'], ['sticker_packs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stickers_id'), 'stickers', ['id'], unique=False)
    op.create_index(op.f('ix_stickers_name'), 'stickers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stickers_name'), table_name='stickers')
    op.drop_index(op.f('ix_stickers_id'), table_name='stickers')
    op.drop_table('stickers')
    op.drop_index(op.f('ix_sticker_packs_name'), table_name='sticker_packs')
    op.drop_index(op.f('ix_sticker_packs_id'), table_name='sticker_packs')
    op.drop_table('sticker_packs')
    # ### end Alembic commands ###
