"""add social economy fields

Revision ID: c57c0be8e270
Revises: e63a77b4848a
Create Date: 2025-11-30 16:06:38.840206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57c0be8e270'
down_revision: Union[str, None] = 'e63a77b4848a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('quality_score', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('originality_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('social_credits', sa.Float(), nullable=False))
    op.create_index(op.f('ix_users_social_credits'), 'users', ['social_credits'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_social_credits'), table_name='users')
    op.drop_column('users', 'social_credits')
    op.drop_column('posts', 'originality_score')
    op.drop_column('posts', 'quality_score')
    # ### end Alembic commands ###
