"""Legacy compatibility layer aggregating SQLAlchemy models.

The application has been modularised under ``app.modules``. This file keeps the
original ``app.models`` import path working by re-exporting the models,
enums, and association tables from their domain packages. New code should
import directly from the relevant module package.
"""

from app.modules.users.associations import post_mentions, user_hashtag_follows
from app.modules.community.associations import community_tags
from app.modules.stickers import sticker_category_association

from app.modules.users.models import (
    UserType,
    VerificationStatus,
    PrivacyLevel,
    UserRole,
    User,
    TokenBlacklist,
    UserActivity,
    UserEvent,
    UserSession,
    UserStatistics,
)

from app.modules.community import (
    CommunityRole,
    CommunityCategory,
    Community,
    CommunityMember,
    CommunityStatistics,
    CommunityRule,
    CommunityInvitation,
    Category,
    SearchSuggestion,
    SearchStatistics,
    Tag,
    Reel,
    Article,
)

from app.modules.posts import (
    CopyrightType,
    SocialMediaType,
    PostStatus,
    ReactionType,
    Reaction,
    Post,
    Comment,
    PostVoteStatistics,
    RepostStatistics,
    PollOption,
    Poll,
    PollVote,
    PostCategory,
    SocialMediaAccount,
    SocialMediaPost,
    post_hashtags,
)

from app.modules.notifications.models import (
    NotificationStatus,
    NotificationPriority,
    NotificationCategory,
    NotificationType,
    NotificationPreferences,
    NotificationGroup,
    Notification,
    NotificationDeliveryAttempt,
    NotificationAnalytics,
    NotificationDeliveryLog,
)

from app.modules.messaging import (
    CallType,
    CallStatus,
    MessageType,
    ScreenShareStatus,
    ConversationType,
    ConversationMemberRole,
    Conversation,
    ConversationMember,
    Message,
    MessageAttachment,
    EncryptedSession,
    EncryptedCall,
    Call,
    ScreenShareSession,
    ConversationStatistics,
)

from app.modules.support import TicketStatus, SupportTicket, TicketResponse

from app.modules.stickers import (
    StickerPack,
    Sticker,
    StickerCategory,
    StickerReport,
)

from app.modules.moderation import (
    BlockDuration,
    BlockType,
    AppealStatus,
    UserWarning,
    UserBan,
    IPBan,
    BannedWord,
    BanStatistics,
    BanReason,
    Block,
    BlockLog,
    BlockAppeal,
)

from app.modules.amenhotep import (
    AmenhotepMessage,
    AmenhotepChatAnalytics,
    CommentEditHistory,
)

from app.modules.social import (
    ReportStatus,
    Hashtag,
    BusinessTransaction,
    Vote,
    Report,
    Follow,
)

__all__ = [
    "post_mentions",
    "user_hashtag_follows",
    "community_tags",
    "sticker_category_association",
    "post_hashtags",
    "UserType",
    "VerificationStatus",
    "PrivacyLevel",
    "UserRole",
    "User",
    "TokenBlacklist",
    "UserActivity",
    "UserEvent",
    "UserSession",
    "UserStatistics",
    "CommunityRole",
    "CommunityCategory",
    "Community",
    "CommunityMember",
    "CommunityStatistics",
    "CommunityRule",
    "CommunityInvitation",
    "Category",
    "SearchSuggestion",
    "SearchStatistics",
    "Tag",
    "Reel",
    "Article",
    "CopyrightType",
    "SocialMediaType",
    "PostStatus",
    "ReactionType",
    "Reaction",
    "Post",
    "Comment",
    "PostVoteStatistics",
    "RepostStatistics",
    "PollOption",
    "Poll",
    "PollVote",
    "PostCategory",
    "SocialMediaAccount",
    "SocialMediaPost",
    "NotificationStatus",
    "NotificationPriority",
    "NotificationCategory",
    "NotificationType",
    "NotificationPreferences",
    "NotificationGroup",
    "Notification",
    "NotificationDeliveryAttempt",
    "NotificationAnalytics",
    "NotificationDeliveryLog",
    "CallType",
    "CallStatus",
    "MessageType",
    "ScreenShareStatus",
    "Message",
    "MessageAttachment",
    "EncryptedSession",
    "EncryptedCall",
    "Call",
    "ScreenShareSession",
    "ConversationStatistics",
    "TicketStatus",
    "SupportTicket",
    "TicketResponse",
    "StickerPack",
    "Sticker",
    "StickerCategory",
    "StickerReport",
    "BlockDuration",
    "BlockType",
    "AppealStatus",
    "UserWarning",
    "UserBan",
    "IPBan",
    "BannedWord",
    "BanStatistics",
    "BanReason",
    "Block",
    "BlockLog",
    "BlockAppeal",
    "AmenhotepMessage",
    "AmenhotepChatAnalytics",
    "CommentEditHistory",
    "ReportStatus",
    "Hashtag",
    "BusinessTransaction",
    "Vote",
    "Report",
    "Follow",
]
