"""Posts domain public exports."""

from .models import (
    CopyrightType,
    SocialMediaType,
    PostStatus,
    ReactionType,
    Reaction,
    Post,
    Comment,
    PostVoteStatistics,
    RepostStatistics,
    PollOption,
    Poll,
    PollVote,
    PostCategory,
    SocialMediaAccount,
    SocialMediaPost,
    post_hashtags,
)
from .schemas import (
    ReactionBase,
    ReactionCreate,
    ReactionCount,
    PostVoteAnalytics,
    PostVoteStatisticsBase,
    PostVoteStatisticsCreate,
    UserVoteAnalytics,
    PostCategoryBase,
    PostCategoryCreate,
    PostCategory as PostCategorySchema,
    PollOption as PollOptionSchema,
    PollData,
    PollCreate,
    PollResults,
    PostBase as PostBaseSchema,
    PostCreate as PostCreateSchema,
    Post as PostSchema,
    PostOut,
    EngagementStats,
    SocialPostBase,
    SocialPostCreate,
    SocialPostUpdate,
    SocialPostOut,
    PostSearch,
)

__all__ = [
    "CopyrightType",
    "SocialMediaType",
    "PostStatus",
    "ReactionType",
    "Reaction",
    "Post",
    "Comment",
    "PostVoteStatistics",
    "RepostStatistics",
    "PollOption",
    "Poll",
    "PollVote",
    "PostCategory",
    "SocialMediaAccount",
    "SocialMediaPost",
    "post_hashtags",
    "ReactionBase",
    "ReactionCreate",
    "ReactionCount",
    "PostVoteAnalytics",
    "PostVoteStatisticsBase",
    "PostVoteStatisticsCreate",
    "UserVoteAnalytics",
    "PostCategoryBase",
    "PostCategoryCreate",
    "PostCategorySchema",
    "PollOptionSchema",
    "PollData",
    "PollCreate",
    "PollResults",
    "PostBaseSchema",
    "PostCreateSchema",
    "PostSchema",
    "PostOut",
    "EngagementStats",
    "SocialPostBase",
    "SocialPostCreate",
    "SocialPostUpdate",
    "SocialPostOut",
    "PostSearch",
    "VoteService",
]


def __getattr__(name: str):
    if name == "VoteService":
        from app.services.posts.vote_service import VoteService as _VoteService

        return _VoteService
    raise AttributeError(f"module 'app.modules.posts' has no attribute {name!r}")
